---
title: "Activity Log" 
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
            warnings = FALSE,
            message = FALSE,
            comment = "#>",
            #results = "hide",
            digits = 4,
            error = FALSE)

library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(gtsummary, quietly = TRUE)
library(flextable, quietly = TRUE)
## check the directory for the file
# here::dr_here()
here::set_here()
```

```{css, echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```


## Activity Log for Development {#sec-activity_log}

### 20250205 {.unnumbered}

-   [x] General SCOPE DCC / Grant Document Review
-   [x] Read through the analytic plan for [Link](https://olucdenver.sharepoint.com/:w:/r/sites/SCOPEDCC/_layouts/15/Doc.aspx?sourcedoc=%7B05AEB1C9-7608-4E75-ACE8-BC9FE35B33D8%7D&file=2-26-2024%20protocol%20with%20track%20changes%20KLC.doc&action=default&mobileredirect=true)
-   [x] This is a clustered randomized trial
    -   [x] section 9.4 Analysis Section
    -   [x] section 11.2 Data Management page 7
    -   [x] write a statistical analysis plan for each analysis
    -   [x] primary - \> caregiver
-   [x] Randy will map the protocol to the databases to the analysis
-   [x] What are the superior hypothesis and reject the $H_0$
-   [x] You are fine!

**Notes: Yizhou is working on the truncated by death cases; probably can be shifted into the primary data analysis plan.**

### 20250305 {.unnumbered}

-   [x] Build up the analysis plan template and the package functions
-   [x] Reference the [SAP paper](https://www.sciencedirect.com/science/article/pii/S0885392422008570)
-   [x] Ask Katie for approval on the package project
-   [x] You are magnificent!

### 20250404 {.unnumbered}

-   [x] Talking with EJC about the package project
-   [ ] Filling up the project and add comments
-   [ ] Build up the analysis plan for multiple members
-   [ ] Check how to build up the website
-   [ ] Check how to use github to include other people
-   [x] You are cat's meow!


### 20250408 {.unnumbered}

-   [x] Filling up the project and add comments
-   [x] Writing functions to create qmd files
-   [x] New aim function and files
-   [ ] Build up the analysis plan for multiple members
-   [ ] Check how to build up the website
-   [ ] Check how to use github to include other people
- [x] You are excellent!


### 20250410 {.unnumbered}

- [ ] how to use argument in the YML
- [ ] generate reports and analysis without coding
- [ ] working on the figure and table
- [ ] aim 1 analysis plan (to Katie)
- [x] You are premium!

### 20250415 {.unnumbered}
Goal for this meeting with Katie

- [x] show the demo case of the template / package 
- [ ] better organize the template
- [ ] add the function to create the qmd file or just copy paste
- [ ] subfolder or generate the files all in one
- [ ] styles and formatting?
- [ ] asking help for the website
- [x] You are swell!


#### 202505


- [x] cleaning out the dataset with R
- [x] table1 with the redcap_repeat_instrument blank
- [x] only have the baseline information
- [x] sensitivity analysis in the futuer (not considering this time)
- [x] involving with Yizhou's work in the furtuer.
- [] the monitoring section? keep it or not. more about the analysis.
we do not want the entire protocol but what we need to do. 
- [] the specific analysis plan for each aim all together. 
- [] the main paper, not by aim but by paper
- [] we can put all the analysis the EDA and paper. and gettign ahead. 
- [] the compos, the variable 12 week, link the names for the dictionary to the variables
the primary and the secondary and the variables in the analysis for the names of the variables
redcap rep the blanks the guide, I can 


- [x] You are wondrous!