---
title: "Background"
format: html
editor: visual
---

Patients with AML have a sudden life-threatening illness requiring urgent therapy AML is an aggressive disease, characterized by an abrupt onset, an urgent need to initiate treatment, and a poor prognosis with 80% risk of death at five years.1-5 Most patients with AML are treated with chemotherapy drugs that require hospitalization due to significant toxicities and potentially life-threatening complications, such as bleeding and sepsis.6-9 Patients with AML often present to medical attention without prodromal symptoms, so they are quite shocked to learn that they have a life-threatening illness and must be immediately hospitalized to receive intensive chemotherapy.1-3

Patients with AML face substantial physical and psychological symptoms During their hospitalization for chemotherapy, patients with AML often experience difficult physical symptoms, including fevers, fatigue, pain, insomnia, mucositis, nausea, vomiting, and diarrhea that negatively impact their quality of life (QOL) and physical function.6-12 Psychological symptoms are also quite prominent in these patients, with over one-third experiencing acute stress reactions from the shock of their diagnosis and need for urgent hospitalization.6-19 Notably, the psychological burden during this hospitalization also impacts patients’ long-term QOL, mood, and adaptation to their illness.18,19 Up to 40% of patients with AML suffer from post-traumatic stress symptoms due to the trauma of their diagnosis.20-23 Therefore, addressing the physical and psychological needs of hospitalized patients with AML has the potential to improve their outcomes significantly both during their hospitalization and in the long-term.

Patients with AML face difficult decisions about treatment Many treatments are available that offer a chance of cure for patients with AML, including stem cell transplant. However, the chance of cure is small and most patients with AML unfortunately die of their illness.24,25 Consequently, to make informed decisions about whether to receive additional treatment, patients with AML must understand their prognosis and likelihood of cure.26,27 Unfortunately, data suggest that 90% of patients with AML report overly optimistic estimates of their prognosis.27 Thus, they are unprepared to make difficult decisions that require them to balance the risk and benefits of treatments that offer an uncertain chance of cure, but will worsen their QOL and require them to spend additional time in the hospital. In fact, patients with AML spend approximately 50% of their life from the time of diagnosis until death in the hospital.9 Therefore, patients with AML face considerable uncertainty and often misunderstand their prognosis, limiting their ability to make informed decisions about treatment.

Patients with AML rarely discuss their end-of-life (EOL) care preferences Due to the chance of cure even after multiple therapies, oncology clinicians often defer engaging in conversations with patients with AML about their EOL care preferences.26 As the majority of these patients die, it is imperative that oncology clinicians elicit their goals and help them make decisions about their EOL care. Unfortunately, studies show that patients with AML do not engage in timely discussions with their clinicians about their care preferences and consequently receive aggressive care at the EOL.18,28-35 Specifically, while many patients with cancer express a preference to die at home and minimize time in the hospital, 80% of patients with AML are hospitalized in the last month of life, with 50% dying in the hospital. Over half receive chemotherapy in the last month of life and 30% die in the intensive care unit (ICU).18,28-35 Evidence-based interventions are needed to enhance patient-clinician communication and optimize EOL care for patients with AML.

Caregivers of patients with AML experience tremendous burden and distress The family and close friends (“caregivers”) of patients with AML play a critical role in their care, but also experience distress as they face the shock of the patient’s diagnosis and cope with uncertainty.10,36-38 During the patient’s hospitalization for treatment, caregivers report a marked decline in their QOL and mood as they witness the patient struggle with side effects.10 After the patient is discharged from the hospital, the caregiver helps manage the patient’s symptoms, attends multiple oncology appointments, coordinates medical care, and prepares for subsequent hospitalizations.39 Caregivers experience the highest burden and psychological distress when caring for patients with AML near the EOL.39,40 Not surprisingly, caregivers of patients with AML have disruptions in their professional and personal lives. Thus, caregivers of patients with AML would benefit from support as they navigate the patient’s illness.

Specialty palliative care improves outcomes for patients and their caregivers A growing body of evidence has demonstrated the essential role of specialty palliative care (PC) clinicians in the care of patients with advanced solid tumors.41-45 Integrating PC with oncology care from the time of diagnosis for patients with advanced solid tumors improves patients’ QOL, psychological health, and EOL care.41-45 Emerging data have similarly shown the benefits of specialty PC for patients with hematologic malignancies.46-48 We recently completed a multi-site randomized trial of specialty PC versus usual care in hospitalized patients with AML.48 Patients assigned to specialty PC met with a PC clinician at least twice weekly during their hospitalization for chemotherapy and subsequent hospitalizations up to one year. Specialty PC improved patients’ QOL, depression and anxiety symptoms, as well as post-traumatic stress symptoms.48 Importantly, specialty PC led to clinically meaningful and sustained improvements in patients’ QOL and psychological distress for six months after initiating chemotherapy.48 Patients receiving specialty PC were also more likely to discuss their EOL care preferences and less likely to receive chemotherapy in the last month of life.48 Thus, involvement of specialty PC improves the experience and outcomes of patients with serious cancer and their caregivers.

Specialty PC is not an accessible or scalable care model Despite the benefits of specialty PC for patients with cancer, it is not feasible to provide this care for all patients given the limited availability of trained PC clinicians.49-51 Nearly half of National Cancer Institute-designated cancer centers do not have the specialty PC workforce to provide care for their patients with cancer.49-51 Due to these workforce shortages, most specialty PC is triaged to provide care for patients with incurable cancer at the EOL. Thus, despite the growing evidence base, substantial challenges limit the scalability and dissemination of this care model, especially in caring for patients with hematologic malignancies.26,52 Moreover, oncology clinicians caring for patients with hematologic malignancies rarely consult specialty PC as they view providing PC within their scope of practice.26,53-55 Furthermore, given the complex chemotherapy regimens used to treat patients with AML and their side effects, oncology clinicians may be the ideal clinicians to address these needs.26,53-55

Primary PC may be an alternative care model to specialty PC Training oncology clinicians to incorporate PC skills into their care practice (i.e., “primary PC”) is an alternative strategy to having specialty trained PC clinicians care for all patients with cancer. Recent studies have shown that primary PC interventions in which oncology clinicians are trained to address patient’s symptoms and engage in serious illness conversations are feasible, acceptable, and improve patient outcomes.56,57 These interventions have been shown to increase oncology clinicians’ knowledge about symptom assessment and management, as well as their comfort managing psychological distress.58-60 In a cluster randomized trial in which oncology clinicians were trained in serious illness communication, patients receiving primary PC were more likely to have documented EOL discussions and reported lower anxiety and depression symptoms.56,57 While these primary PC studies are promising, it remains unknown how primary PC compares with specialty PC for improving QOL and EOL care for patients with cancer.26,61 Recent systematic reviews highlight the need for comparative effectiveness trials of primary versus specialty PC, to determine how to best meet the needs of patients with serious cancers, and especially those with hematologic malignancies.26,61
