---
title: "Aims and Hypotheses"
format: html
editor: visual
---

## Aims and Hypotheses


### Aim 1 
To determine whether primary PC is non-inferior to specialty PC for improving QOL in patients with AML: We will begin with descriptive and graphical summaries of the endpoints to evaluate whether regression modeling assumptions are met and/or whether there are outliers that might be data entry errors. We will use an intention-to-treat approach for treatment group comparisons and report results using the CONSORT extension to cluster randomized trials. We chose an intention-to-treat approach for the primary analysis in our study as it 1) preserves the advantage of randomization and 2) we anticipate minimal cross-contamination in this cluster randomized clinical trial between study groups, which further enhances the fidelity of an intention-to-treat analysis. Nonetheless, we will closely track the extent of contamination in both study groups. We will also assess for potential factors that are associated with non-adherence to the assigned PC model such as age, sex, race/ethnicity, time from diagnosis, underlying leukemia diagnosis, leukemia risk, and institutional factors that might be associated with non-adherence (leukemia volume, size of leukemia program, and other institutional supportive care initiatives). We will also conduct and report per protocol analyses using inverse probability weighting (IPW) to provide robust statistical estimates for the primary and secondary outcomes in this trial. As the goal of the proposed study is to establish that patient-reported QOL with primary PC is non-inferior to specialty PC, all statistical tests for non-inferiority will be one-sided with an alpha level of 0.025. The primary endpoint of the study is to compare patient QOL (FACT-Leukemia) scores at week 12 between the study groups using linear mixed (LMM) effect models of longitudinal data with QOL estimated at each time point, with random effects for cluster and subject. The use of mixed models will allow us to account for dependency among longitudinal outcomes within a cluster and within an individual and to control for demographic and clinical factors (as necessary for any imbalances in baseline variables). Each time point will be included as a fixed factor with baseline as the reference group. Lastly, we will test for Heterogeneity of Treatment Effect (HTE) based on age, gender, race/ethnicity, AML diagnosis (newly diagnosed vs. relapsed/refractory), and enrollment of caregiver using interaction terms in the mixed models (see HTE analysis plan). We will utilize a similar strategy when comparing patient-reported depression (HADS-depression), anxiety (HADS-anxiety), PTSD symptoms (PTSD-Checklist), coping (Brief COPE), symptom burden (ESAS-r), and perception of centeredness of care (PPPC) between the two groups. The mixed models also permit inclusion of patients who only provide partial longitudinal data so that all available data are contributing to the analysis.

### Aim 2
To assess whether primary PC is non-inferior to specialty PC for improving patient-clinician EOL communication: We will examine patient-report of discussing EOL care preferences with their clinicians using the following item: “Have you and your doctors discussed any particular wishes you have about the care you would want to receive if you were dying?” (Yes/No). Although patients will complete this measure repeatedly during the study, we will use the final assessment either prior to death or at last follow-up assessment point (whichever comes first) for this analysis. We will compare differences between study groups in the rate of patients reporting “Yes” to this item using a binomial generalized linear mixed effects model with an identity link function, adjusting for any demographic and clinical factors that are imbalanced between the two groups (non-inferiority margin of 13%) and a single random effect for cluster. Utilizing a similar statistical approach, we will conduct an exploratory analysis comparing patient and caregiver prognostic understanding using the response to the following item of the PTPQ: “What is the likelihood that you will be cured of your leukemia?” Responses will be dichotomized as accurate versus inaccurate as done in prior studies. Although patients and caregivers will complete this measure repeatedly during the study, we will also use the final assessment either prior to death or at 24 weeks (whichever comes first) for this analysis.

### Aim 3
To compare the effect of primary PC versus specialty PC on EOL outcomes for patients with AML: We will compare chemotherapy use (yes/no; non-inferiority margin 15%) using a binomial generalized linear mixed effects model with an identity link function, adjusting for any demographic and clinical factors that are imbalanced between the two groups. We will also explore differences in hospitalizations (yes/no), ICU admissions (yes/no), and hospice utilization (yes/no) in the last 30 days of life between the two study groups using mixed effect logistic regression models. We will explore differences in hospice length-of-stay between primary PC and specialty PC using linear mixed effects models adjusting for imbalances between the two groups.

### Aim 4
To compare the effect of primary PC versus specialty PC on caregiver QOL and psychological distress: We will assess the non-inferiority of primary PC versus specialty PC on caregiver QOL (CarGOQOL, non-inferiority margin 5 points), depression (HADS-Depression, non-inferiority margin 1.5 points), anxiety (HADS-anxiety, non-inferiority margin 1.5 point) symptoms at week-12 using linear mixed effects models. We will also utilize mixed models when differences between groups in these outcomes at multiple time points (i.e., baseline, weeks 2, 4, 12, and 24).

### Aim 5 
Qualitative analyses based on RE-AIM Quest: Trained study staff will conduct audio-recorded qualitative interviews with patients, caregivers, oncology and PC clinicians, and hospital leaders. Data analyses will co-occur with interview data collection to ascertain if thematic saturation (the point at which no new data are generated) has been achieved for each stratum (i.e., small, medium, or large leukemia programs). All interviews will be recorded, transcribed, and analyzed using NVivo 12 qualitative software. Two independent coders will analyze the interview content thematically, overseen by Dr. Park. Guided by RE-AIM, the coders will meet to develop the thematic framework and coding plan. Each interview will be coded twice. Interpretation and analysis of coded transcripts will follow the RE-AIM framework: 1) reach, 2) effectiveness, 3) adoption, 4) implementation, and 5) maintenance. To ensure coding reliability, coding discrepancies will be resolved through discussion and comparison of raw data. Coding will continue until a high level of reliability (kappa > 0.80) is established. Individual interview results will be analyzed by strata comparisons. After the dataset is complete, the study team will conduct independent expert reviews of the data prior to integration with quantitative data.
