---
title: "Interested Variables"
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
            warnings = FALSE,
            message = FALSE,
            comment = "#>",
            #results = "hide",
            digits = 4,
            error = FALSE)
# ## clean the R environment
# graphics.off()
# rm(list = ls())
# freshr::freshr()
# ## load packages
# library(here, quietly = TRUE)
# library(tidyverse, quietly = TRUE)
# library(gtsummary, quietly = TRUE)
# library(flextable, quietly = TRUE)
# ## check the directory for the file
# # here::dr_here()
# here::set_here()
## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#      Sys.Date(), ".filetype")
```

```{css, echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

## Outcomes variables {#sec-outcomes}


List of all outcome/endpoint variables, 
with a description of their coding/units, timing, and source, 
corresponding to the statistical hypotheses. 
If any variables are defined using ICD or CPT codes, list them out.


## Exposure variables {#sec-exposures}


List of all exposure variables, 
with a description of their coding/units, timing, and source,
corresponding to the statistical hypotheses. 
If any variables are defined using ICD or CPT codes, list them out.


## Additional variables {#sec-additional}

List of any additional variables of interest 
(e.g. covariates, potential confounders, effect modifiers, etc.) in the analysis.



## Data dictionary {#sec-dictionary}

Location of data dictionary (or provided as an appendix)




## Data transformations {#sec-transformations}

Report category boundaries if continuous variables are collapsed into categories,
and describe any other relevant data transformations








