---
title: "Statistical Analysis"
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
            warnings = FALSE,
            message = FALSE,
            comment = "#>",
            #results = "hide",
            digits = 4,
            error = FALSE)

```

```{css, echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

## Significance

Hypothesis testing framework (e.g. superiority, equivalence, non-inferiority), or description of
alternative analytic framework (e.g. evaluation of a posterior in a Bayesian analysis, etc.)
Level of significance for primary hypotheses, including a description and rationale for any
multiple comparisons adjustment or Type I error control procedures
Description of any decision-making rules based on confidence intervals, credible intervals,
prediction intervals, Bayes’ factors, or other alternative inferential methods
Description of how the results of any hypothesis tests (or alternative inferential methods) will
be interpreted with respect to both the statistical hypotheses and scientific aims/objectives of the
study