---
title: "Study Overview"
format: html
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
            warnings = FALSE,
            message = FALSE,
            comment = "#>",
            #results = "hide",
            digits = 4,
            error = FALSE)
```

```{css, echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```


## Objective {#sec-objective}

This is a cluster randomized comparative effectiveness trial of primary palliative care (PC) versus specialty PC in 1150 patients with acute myeloid leukemia (AML) and their caregivers. 

The primary objective is to determine whether primary PC is non-inferior to specialty PC for improving quality of life (QOL) in patients with AML.  The primary hypothesis is that patients assigned to primary PC will report QOL that is non-inferior to patients receiving specialty PC, with a non-inferiority margin of 5.0 points. This study includes several secondary and exploratory endpoints as described in section @sec-endpoints.


## Study-Wide Number of Subjects {#sec-number_of_subjects}

The study sample will include 1150 patients with AML and up to 1150 caregivers.  Patients can participate in the study without a caregiver, and we estimate that approximately 50% of patients will have a caregiver participate in the study. Thus, we anticipate the caregiver sample will be approximately 575 participants.

