---
title: "Multi-Site Research"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
            warnings = FALSE,
            message = FALSE,
            comment = "#>",
            #results = "hide",
            digits = 4,
            error = FALSE)
```

```{css, echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

## Multi-Site Research

### Clinical Coordinating Center (CCC) {#sec-ccc}

MGH will serve as the Clinical Coordinating Center (CCC) for this trial. 
The CCC will:

- 1) conduct trainings for site PIs and CRCs to ensure consistent recruitment and enrollment procedures across sites, for PC clinicians for sites randomized to specialty PC, and  oncology clinicians for sites randomized to primary PC; 
- 2) ensure regulatory compliance across sites by obtaining single IRB reliance agreements; 
- 3) perform site visits to monitor study progress and ensure compliance with study procedures; 
- 4) conduct monthly meetings with the site PIs and CRCs to address any study issues and challenges; 
- 5) review data collection reports generated by the Data Coordinating Center (DCC) and provide feedback to the site PIs to ensure high-data quality; 
- 6) review intervention fidelity reports generated by the DCC and provide feedback to individual clinicians at participating sites to ensure adherence to intervention delivery. 

### Study Staff Training {#sec-sst}

We will conduct an in-person training (or over video given COVID-19 pandemic) at MGH for the site PIs and the CRCs to ensure consistent enrollment procedures across sites. We will train the investigative team in how to:

- 1) identify potentially eligible patients; 
- 2) communicate with leukemia clinicians about patient eligibility; 
- 3) obtain informed consent from patients and caregivers; 
- 4) ensure intervention delivery and data collection. 

### Data Coordinating Center (DCC) Functions {#sec-dcc}

<mark>**Data and Statistics Organization and Function:**</mark> The DCC will lead the design and implementation of the statistics, informatics, and data management systems for the study. As part of the University of Colorado Data Informatics and Statistics Core, the DCC will work with the MGH investigative team to develop, implement, and maintain systems for a central data repository. The DCC has substantial expertise in statistical design and analysis, and creation of a standardized data element (SDE) dictionary with a case report form (CRF) library. <mark>The DCC will act independently in its management and analysis of data</mark>; however, the development of the data collection systems will be done in collaboration with the MGH investigative team. 

All data collected at participating sites will remain confidential and will be collected via REDCap. Identifiers such as name will only be used during the initial data retrieval process and can be destroyed once all data records have been obtained and data analysis completed. All protected health information will be labeled as such in REDCap with only site personnel having access to protected health information at their respective sites. The MGH study team and the DCC will also have access to protected health information at all study sites via REDCap to conduct data monitoring queries and ensure data fidelity. 


### Setting

Participants will be recruited for study participation across 20 sitesPatients will be approached for study participation in their private hospital room during their hospitalization for AML. Caregivers will be approached for study participation in-person in a private hospital room or over the telephone. For completion of follow-up assessments, participants can be approached on the inpatient unit in a private room, during a clinic visit in a private space, or over the telephone.
