---
title: "Missing Data"
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
            warnings = FALSE,
            message = FALSE,
            comment = "#>",
            #results = "hide",
            digits = 4,
            error = FALSE)
# ## clean the R environment
# graphics.off()
# rm(list = ls())
# freshr::freshr()
# ## load packages
# library(here, quietly = TRUE)
# library(tidyverse, quietly = TRUE)
# library(gtsummary, quietly = TRUE)
# library(flextable, quietly = TRUE)
# ## check the directory for the file
# # here::dr_here()
# here::set_here()
## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#      Sys.Date(), ".filetype")
```

```{css, echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

## Missing Data {#sec-missing_data}
Description of sources and magnitudes of missing data

As in our prior PC trials, we will utilize rigorous methodology in reporting reasons for dropout and missing data during the study period including: 1) patient death; 2) inability to complete the study due to illness; 3) transfer of care; 4) withdrawal of consent; and 5) unable to contact for follow-up. The investigative team will review missing data rates for all participating sites to address any discrepancies in missing data compared to prior studies and to ensure rigorous retention and follow-up procedures. We will use the ITT principle with all randomized subjects, conducting sensitivity analyses to explore how various assumptions about missing data and differences between completers and non-completers affect the estimated outcomes. We will include all available data for analysis of primary and secondary outcomes. Some patients may have missing covariate or outcomes data. Zhao and Ding showed that greater precision and efficiency can be achieved by using a single imputation (such as mean imputation) plus a missing variable indicator for each missing covariate in regression models for analysis of randomized trials, even when data are missing not at random (MNAR). We will use this approach for inclusion of covariates in all mixed models. Missing outcome data will not be imputed in the primary analysis; however, patients can contribute any number of time points in the mixed regression model (i.e., completion of all time points is not required) and the maximum likelihood–based estimates are valid if data are missing at random. Additional sensitivity analyses may also be conducted in handling missing data (e.g., employing pattern mixture modeling or joint modeling approaches), under the direction of the DCC.


## Missing Patterns {#sec-missing_patterns}
Description of how missing data patterns will be presented/summarized (may be helpful to have a table shell or draft CONSORT-style diagram)

## Missing Strategies {#sec-missing_strategies}
Description of contingency plans for handling missing data in analysis










