---
title: "Aim1 Sample Size"
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      #results = "hide",
                      digits = 4,
                      error = FALSE)
```

```{css, echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

## DATA SOURCES 

(identify existing data and additional data needed): 

### Electronic Health Records (EHR)
-	Collection of end-of-life (EOL) care data.
-	Baseline clinical, disease, and treatment information, including:
    - ECOG performance status.
    - Clinical comorbidities (Sorror Comorbidity Index).
    - AML type, diagnosis, and disease risk 
    (Disease Risk Index, cytogenetics, and mutations).
    -AML recurrence and additional treatments, including stem cell transplantation.
    
### REDCap

-	A secure, HIPAA-compliant web-based application for data collection and management.
-	Storing data abstracted from EHR.
-	Weekly palliative care (PC) surveys completed by clinicians.
-	Maintaining study-related data securely

### Data Coordinating Center (DCC)

-	Centralized data repository for all sites.
-	Responsible for data cleaning, quality checks, and analysis.
-	Generates monthly reports on study progress, enrollment, and intervention fidelity

